image: archlinux/base:latest

stages:
    - linting
    - dependencies

linting:
    stage: linting
    before_script:
        - pacman -Syu --noconfirm 
        - pacman -S flake8 --noconfirm
    script:
        - python3 -m flake8
    tags:
        - shared

dependencies:
    stage: dependencies
    before_script:
        - pacman -Syu --noconfirm
        - pacman -S python-pip
    script:
        - pip install -r requirements.txt
    tags:
        - shared
