image: archlinux/base:latest

stages:
    - linting
    - dependencies
    - build

linting:
    stage: linting
    before_script:
        - pacman -Syu --noconfirm 
        - pacman -S flake8 --noconfirm
    script:
        - python3 -m flake8
    tags:
        - shared

dependencies:
    stage: dependencies
    before_script:
        - pacman -Syu --noconfirm
        - pacman -S python-pip --noconfirm
    script:
        - pip install -r requirements.txt
    tags:
        - shared

build package:
    stage: build
    before_script:
        - pacman -Syu --noconfirm
        - pacman -S python-pip --noconfirm
    script:
        - pip install --upgrade setuptools wheel
        - python3 setup.py sdist bdist_wheel
    only:
        - tags
    tags:
        - shared
